apiVersion: batch/v1
kind: Job
metadata:
    name: garbagecollectionjob
    namespace: garbage-collection
    labels:
        app: garbagecollectionjob
spec:
    activeDeadlineSeconds: 300
    backoffLimit: 1
    ttlSecondsAfterFinished: 0
    completions: 2
    parallelism: 2
    # selector:
    #     matchLabels:
    #         app: garbagecollectionjob
    template:
        metadata:
            labels:
                app: garbagecollectionjob
        spec:
            priorityClassName: high-priority
            restartPolicy: Never
            affinity:
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: app
                        operator: In
                        values:
                        - garbagecollectionjob
                    topologyKey: "kubernetes.io/hostname"

            containers:
            - name: garbagecollectionjob
              image: alpine:edge
              command: ["/bin/sh", "-c", "apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing cri-tools bash && ./clean.sh && sleep 300"] # && crictl -r unix:///run/containerd/containerd.sock rmi --prune"]
              volumeMounts:
              - name: docker-mount
                mountPath: /run/containerd/containerd.sock
              - name: script
                mountPath: /clean.sh
                subPath: clean.sh

            volumes:
            - name: docker-mount
              hostPath:
                path: /run/containerd/containerd.sock
            - name: script
              configMap:
                name: garbagecollection-configmap
                defaultMode: 0777
