apiVersion: v1
kind: Namespace
metadata:
  name: garbage-collection
---
apiVersion: batch/v1
kind: Job
metadata:
    name: garbagecollectionjob
    namespace: garbage-collection
    labels:
        app: garbagecollectionjob
spec:
    activeDeadlineSeconds: 300
    backoffLimit: 1
    ttlSecondsAfterFinished: 0
    completions: 2
    parallelism: 2
    # selector:
    #     matchLabels:
    #         app: garbagecollectionjob
    template:
        metadata:
            labels:
                app: garbagecollectionjob
        spec:
            priorityClassName: high-priority
            restartPolicy: Never
            affinity:
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: app
                        operator: In
                        values:
                        - garbagecollectionjob
                    topologyKey: "kubernetes.io/hostname"

            containers:
            - name: garbagecollectionjob
              image: alpine:latest
              command: ["/bin/sh", "-c", "apk add --no-cache docker && docker image prune -af && sleep 200"]
              volumeMounts:
              - name: docker-mount
                mountPath: /var/run/docker.sock

            volumes:
            - name: docker-mount
              hostPath:
                path: /var/run/docker.sock
